name: Build and deploy API to Azure Web App - barbershop

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: barbershop-
  PROJECT_PATH: BarberShop.Api/BarberShop.Api.csproj
  DOTNET_VERSION: '8.0.0'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore
        run: dotnet restore ${{ env.PROJECT_PATH }}

      - name: Build
        run: dotnet build ${{ env.PROJECT_PATH }} --configuration Release --no-restore

      - name: Publish
        run: dotnet publish ${{ env.PROJECT_PATH }} --configuration Release --no-build --output ./publish

      - name: Zip publish folder
        run: |
          cd ./publish
          zip -r ../app.zip .

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: ./app.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_C0E3748E30834333AE525577508FB964 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_54FA7AF59FEB482484173E2D3FFDCB41 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_85C44CDFA0FE4AD28BAD074C43B66F14 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          slot-name: Production
          package: app.zip
