name: CI - Build BarberShop

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Restore API
        run: dotnet restore BarberShop.Api/BarberShop.Api.csproj

      - name: Build API
        run: dotnet build BarberShop.Api/BarberShop.Api.csproj --no-restore --configuration Release

      - name: Restore Web
        run: dotnet restore BarberShop.Web/BarberShop.Web.csproj

      - name: Build Web
        run: dotnet build BarberShop.Web/BarberShop.Web.csproj --no-restore --configuration Release
